# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://172.26.31.181:43306/mysqlDB
    username: mysqlDB
    password: TtdhJedbkc3iAXaL
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size:
        10000MB
      max-request-size:
        100000MB

server:
  port: 49000

constants:
  filePath: "C:\\Users\\Draco\\IdeaProjects\\Dropbox-backend\\src\\main\\resources\\file"